import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import Carousel2 from '@/components/Carousel';
import { FiExternalLink } from "react-icons/fi";

import { Slide } from 'react-slideshow-image';
import 'react-slideshow-image/dist/styles.css'


// import Swiper core and required modules
import { Navigation, Pagination, Scrollbar, A11y, Autoplay, EffectCreative, EffectCards } from 'swiper/modules';

import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/autoplay';
import 'swiper/css/effect-creative';
import 'swiper/css/effect-cards';
import { useEffect, useState } from 'react';
import axios from 'axios';
import mongoose from 'mongoose';
import HeroSlider from '@/components/HeroSlider';
// import Notice from '@/models/Notice';


export default function Home({ nLinks }) {


  const images = [
    "https://www.davschool.org/3/img/slider/best-schools-in-rajendra-nagar-patna.png",
    "https://www.davschool.org/3/img/gallery/2.jpg",
    "https://www.davschool.org/3/img/gallery/3.jpg",
    "https://www.davschool.org/3/img/gallery/4.jpg",
    // "https://img.etimg.com/thumb/msid-93051525,width-1070,height-580,imgsize-2243475,overlay-economictimes/photo.jpg",
    // "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Wireless/devjyoti/PD23/Launches/Updated_ingress1242x550_3.gif",
    // "https://images-eu.ssl-images-amazon.com/images/G/31/img23/Books/BB/JULY/1242x550_Header-BB-Jul23.jpg",

  ];

  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    // Add a scroll event listener to track the scroll position
    const handleScroll = () => {
      const scrollY = window.scrollY;
      // Show the button if the user scrolls down more than 300 pixels
      setIsVisible(scrollY > 300);
    };

    window.addEventListener('scroll', handleScroll);

    // Clean up the event listener when the component unmounts
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: 'smooth', // Smooth scroll animation
    });
  };


  const [EventList, setEventList] = useState([]);
  useEffect(() => {
    const fetchEvents = async () => {
      const endpoint = `${process.env.NEXT_PUBLIC_HOST}/api/event/getevents`;
      try {
        const res = await axios.get(endpoint);
        const result = await res.data;
        if (result.success) {
          setEventList(result.EventList);
        }
      } catch (error) {
        console.log({ error: "Some Error Occurred" });
      }

    }

    fetchEvents();
    const currdate = new Date().toLocaleDateString();
    console.log(currdate)
    // console.log("first ", currdate.toLocaleTimeString())
  }, [])



  const [NoticeList, setNoticeList] = useState([]);
  useEffect(() => {
    const fetchEvents = async () => {
      const endpoint = `${process.env.NEXT_PUBLIC_HOST}/api/notice/getnotice`;
      try {
        const res = await axios.get(endpoint);
        const result = await res.data;
        if (result.success) {
          setNoticeList(result.NoticeList);
        }
      } catch (error) {
        console.log({ error: "Some Error Occurred" });
      }

    }

    fetchEvents();
  }, [])

  console.log("Notice =.>", NoticeList)


  const spanStyle = {
    padding: '20px',
    background: 'transparent',
    color: 'white'
  }

  const divStyle = {
    display: 'flex',
    alignItems: 'end',
    justifyContent: 'center',
    backgroundSize: 'cover',
  }

  const slideImages = [
    {
      url: '/slider/aatma.png',
      caption: 'Sages Bhopalpatanam'
    },
    {
      url: '/slider/aatma2.png',
      caption: 'Sages Bhopalpatanam'
    },
    {
      url: '/slider/aatma3.png',
      caption: 'Sages Bhopalpatanam'
    },
    {
      url: '/slider/aatma4.png',
      caption: 'Sages Bhopalpatanam'
    },
  ];



  return (
    <>
      <Head>
        <title>SAGES, Bhopalpatnam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-screen overflow-x-hidden' style={{ backgroundImage: 'url(/texture/leaves.webp)' }}>
        
        {/* Hero Section */}
        <section data-aos="fade-in">
          <HeroSlider />
        </section>

        {/* Welcome Message Section*/}
        <section className="welcome" data-aos="fade-up">
          <div className="flex flex-col justify-center items-center pt-12 mx-5 my-12">

            <div className="section-heading flex justify-center text-center">
              <h2 className={styles.sectionTitle}>Welcome to Sages <br />Bhopalpatnam</h2>
            </div>

            <div className="wel-message mx-2 md:mx-20 my-12 text-md text-justify">
              <p className={styles.welcomeMessage}><b>SAGES School</b><span>&nbsp;</span>
                <span className="text-red-700">Affiliated to CBSE upto  senior secondary</span>
                ( A Unit of Nav Jagriti Educational Trust Co-Educational English Medium )
                <span className=" text-blue-500"> <b>NOC granted </b></span>
                <span className="text-danger">
                  SWAMI ATMANAND GOVERNMENT ENGLISH SCHOOL, Bhopalpatnam : </span> <b>'SAGES'</b> founded in 2022 by CG Government has grown today as the largest Government English medium School in the State, managing over 754 educational institution in 33 Districts
                <Link href="about.php" className="bg-red-700 text-white rounded-lg px-1"> Read More...</Link>
              </p>
            </div>
          </div>
        </section>

        {/* Activity Section */}
        <section className="upcoming-activity" data-aos="fade-down">
          <div className="container mx-auto md:px-5 py-12">
            <div className="flex flex-wrap -mx-4 -my-8 px-3">

              {/* Left one */}
              <div className="md:w-1/5 w-full flex flex-col items-center py-10 md:px-4">

                <div className="section-heading flex text-center justify-center">
                  <h2 className={styles.sectionTitle}>Upcoming Activity</h2>
                </div>

                <div className='events space-y-8 my-5 h-[400px]'>

                  {/* {EventList && EventList.map((item, index) => {
                    const cc = parseInt(item.eventDate.split('-')[0]);
                    const mm = item.eventDate.split("-")[1]
                    if (cc > new Date().getDate()) {
                      return (
                        <div><h4 className='text-red-600'>{cc}</h4></div>
                      )

                    }

                  })} */}
                  <div className='bg-blue-300 p-2' style={{ backgroundImage: 'url(/texture/more-leaves.png)' }}>
                    <h4 className='text-sm font-semibold'>Interaction for Class NC & I (ALONG WITH CHILD)</h4>
                    <div className='flex flex-col font-mono'>
                      <span><i></i> 15th March</span>
                      <span><i></i> 5.00 AM to 9.00 PM</span>
                    </div>
                  </div>

                  <div className='bg-red-300 p-2' style={{ backgroundImage: 'url(/texture/y-so-serious-white.png)' }}>
                    <h4 className='text-sm font-semibold'>Interaction for Class NC & I (ALONG WITH CHILD)</h4>
                    <div className='flex flex-col font-mono'>
                      <span><i></i> 15th March</span>
                      <span><i></i> 5.00 AM to 9.00 PM</span>
                    </div>
                  </div>

                  <div className='bg-orange-400 p-2'>
                    <h4 className='text-sm font-semibold'>Interaction for Class NC & I (ALONG WITH CHILD)</h4>
                    <div className='flex flex-col font-mono'>
                      <span><i></i> 15th March</span>
                      <span><i></i> 5.00 AM to 9.00 PM</span>
                    </div>
                  </div>

                </div>

              </div>

              {/* Middle one */}
              <div className='flex w-full md:w-3/5 flex-col md:py-10 md:px-8'>
                <div className="section-heading flex text-center justify-center">
                  <h2 className={styles.sectionTitle}>Achievement / Creativity of Sages</h2>
                </div>

                <div className='py-8 border-2 border-white'>
                  <Slide>
                    {slideImages.map((slideImage, index) => (
                      <div key={index}>
                        <div className="h-[200px] w-full md:h-[400px]" style={{ ...divStyle, 'backgroundImage': `url(${slideImage.url})` }}>
                          <span style={spanStyle}>{slideImage.caption}</span>
                        </div>
                      </div>
                    ))}
                  </Slide>
                </div>

              </div>

              {/* Right one */}
              <div className="flex flex-col w-full md:w-1/5 py-8">

                <div className="section-heading mx-auto">
                  <h2 className={styles.sectionTitle}>What's New</h2>
                </div>

                <div className="relative flex flex-col overflow-hidden mt-10 bg-[#6e9466] rounded-md">

                  <ul
                    className={`space-y-2 list-none text-sm font-sans px-2 py-3 ${styles.marqueeContainer} 
                    h-[400px] flex-wrap animate-marquee text-white ease-in-out `}>


                    {NoticeList && NoticeList.map((item, index) => (
                      <div key={index}>
                        <li className='flex flex-row space-x-2 hover:underline hover:translate-x-2 hover:text-[#d5f5e4]
                     transition duration-300 ease-in-out delay-150 hover:scale-110 px-1'>
                          <FiExternalLink size={35} className='text-red-700' />
                          <span className='flex flex-wrap'>
                            <Link href={item.noticeLink} className='text-xs' >{item.noticeTitle}</Link>
                            <span >
                              <img src="/texture/new.gif" style={{ width: "35px", height: "20px" }} alt="" />
                            </span>
                          </span>

                        </li>
                        <hr />
                      </div>
                    ))}

                  </ul>

                </div>

              </div>


            </div>
          </div>
        </section>

        {/* Congratulations Section*/}
        <section className="congratulations" data-aos="fade-left">
          <div className="congo flex flex-col items-center px-4 md:px-4 my-5 md:mx-auto">

            <div className="section-heading ">
              <h2 className={styles.sectionTitle}>Congratulations</h2>
            </div>

            <div className="flex w-full flex-col md:flex-col items-center md:justify-evenly 
            my-10 mx-10 space-y-8 text-white py-12 rounded-md" style={{ background: 'linear-gradient(45deg, #bd9731, #df5919)' }}>

              <div className='flex my-2 border-2 p-2 bg-orange-300 text-orange-600 rounded-md'>
                <h2 className='text-4xl font-medium text-center'>Achievers</h2>
              </div>

              {/* <div className='flex flex-col justify-center items-center container mx-auto  md:flex-row
               md:space-x-40 space-y-10 bg-blue-600'> */}
              <div className='flex justify-center items-center space-y-12 md:space-y-0 md:py-4 flex-col md:flex-row md:space-x-40'>
              

                <div className="Class-X w-[30vh]">
                  
                  <Swiper
                    // install Swiper modules
                    modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay, EffectCreative]}
                    spaceBetween={100}
                    slidesPerView={1}
                    // navigation
                    autoplay={{
                      delay: 1500,
                      disableOnInteraction: false,
                    }}
                    grabCursor={true}
                    effect={'creative'}
                    creativeEffect={{
                      prev: {
                        shadow: true,
                        translate: [0, 0, -400],
                      },
                      next: {
                        translate: ['100%', 0, 0],
                      },
                    }}
                    // pagination={{ clickable: true }}
                    scrollbar={{ draggable: true }}
                  // onSwiper={(swiper) => console.log(swiper)}
                  // onSlideChange={() => console.log('slide change')}
                  >


                    <SwiperSlide>
                      <div className="item-1 flex flex-col items-center px-10 py-2 rounded-md border-blue border-4 space-y-4 "
                        style={{background: '#c09639', opacity: '1'}}>
                        <h4 className='font-semibold text-md flex text-center'>Class X Toppers</h4>
                        <Image style={{ width: "auto", height: "auto" }} className='rounded-3xl' src='/students/Ritesh-Singh.png' width={160} height={150} alt='image' />
                        <p className='font-normal'>Ritesh Singh</p>
                      </div>
                    </SwiperSlide>

                    <SwiperSlide>
                      <div className="item-1 flex flex-col items-center px-10 py-2 rounded-md border-blue border-4 space-y-4 " 
                      style={{background: '#c09639', opacity: '1'}}>
                        <h4 className='font-semibold text-md text-center'>Class X Toppers</h4>
                        <Image style={{ width: "auto", height: "auto" }} className='rounded-3xl' src='/students/Ritesh-Singh.png' width={160} height={150} alt='image' />
                        <p className='font-normal'>Ritesh Singh</p>
                      </div>
                    </SwiperSlide>

                    <SwiperSlide>
                      <div className="item-1 flex flex-col items-center px-10 py-2 rounded-md border-blue border-4 space-y-4 "
                       style={{background: '#c09639', opacity: '1'}}>
                        <h4 className='font-semibold text-md text-center'>Class X Toppers</h4>
                        <Image style={{ width: "auto", height: "auto" }} className='rounded-3xl' src='/students/Kashish-Singh.png' width={160} height={150} alt='image' />
                        <p className='font-normal'>Kashish Singh</p>
                      </div>
                    </SwiperSlide>

                  </Swiper>
                </div>

                <div className="Class-X w-[30vh]">
                  
                  <Swiper
                    // install Swiper modules
                    modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay, EffectCreative]}
                    spaceBetween={100}
                    slidesPerView={1}
                    // navigation
                    autoplay={{
                      delay: 1500,
                      disableOnInteraction: false,
                    }}
                    grabCursor={true}
                    effect={'creative'}
                    creativeEffect={{
                      prev: {
                        shadow: true,
                        translate: [0, 0, -400],
                      },
                      next: {
                        translate: ['100%', 0, 0],
                      },
                    }}
                    // pagination={{ clickable: true }}
                    scrollbar={{ draggable: true }}
                  // onSwiper={(swiper) => console.log(swiper)}
                  // onSlideChange={() => console.log('slide change')}
                  >


                    <SwiperSlide>
                      <div className="item-1 flex flex-col items-center px-10 py-2 rounded-md border-blue border-4 space-y-4 "
                        style={{background: '#c09639', opacity: '1'}}>
                        <h4 className='font-semibold text-md flex text-center'>Class X Toppers</h4>
                        <Image style={{ width: "auto", height: "auto" }} className='rounded-3xl' src='/students/Ritesh-Singh.png' width={160} height={150} alt='image' />
                        <p className='font-normal'>Ritesh Singh</p>
                      </div>
                    </SwiperSlide>

                    <SwiperSlide>
                      <div className="item-1 flex flex-col items-center px-10 py-2 rounded-md border-blue border-4 space-y-4 " 
                      style={{background: '#c09639', opacity: '1'}}>
                        <h4 className='font-semibold text-md text-center'>Class X Toppers</h4>
                        <Image style={{ width: "auto", height: "auto" }} className='rounded-3xl' src='/students/Ritesh-Singh.png' width={160} height={150} alt='image' />
                        <p className='font-normal'>Ritesh Singh</p>
                      </div>
                    </SwiperSlide>

                    <SwiperSlide>
                      <div className="item-1 flex flex-col items-center px-10 py-2 rounded-md border-blue border-4 space-y-4 "
                       style={{background: '#c09639', opacity: '1'}}>
                        <h4 className='font-semibold text-md text-center'>Class X Toppers</h4>
                        <Image style={{ width: "auto", height: "auto" }} className='rounded-3xl' src='/students/Kashish-Singh.png' width={160} height={150} alt='image' />
                        <p className='font-normal'>Kashish Singh</p>
                      </div>
                    </SwiperSlide>

                  </Swiper>
                </div>

                <div className="Class-X w-[30vh]">
                  
                  <Swiper
                    // install Swiper modules
                    modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay, EffectCreative]}
                    spaceBetween={100}
                    slidesPerView={1}
                    // navigation
                    autoplay={{
                      delay: 1500,
                      disableOnInteraction: false,
                    }}
                    grabCursor={true}
                    effect={'creative'}
                    creativeEffect={{
                      prev: {
                        shadow: true,
                        translate: [0, 0, -400],
                      },
                      next: {
                        translate: ['100%', 0, 0],
                      },
                    }}
                    // pagination={{ clickable: true }}
                    scrollbar={{ draggable: true }}
                  // onSwiper={(swiper) => console.log(swiper)}
                  // onSlideChange={() => console.log('slide change')}
                  >


                    <SwiperSlide>
                      <div className="item-1 flex flex-col items-center px-10 py-2 rounded-md border-blue border-4 space-y-4 "
                        style={{background: '#c09639', opacity: '1'}}>
                        <h4 className='font-semibold text-md flex text-center'>Class X Toppers</h4>
                        <Image style={{ width: "auto", height: "auto" }} className='rounded-3xl' src='/students/Ritesh-Singh.png' width={160} height={150} alt='image' />
                        <p className='font-normal'>Ritesh Singh</p>
                      </div>
                    </SwiperSlide>

                    <SwiperSlide>
                      <div className="item-1 flex flex-col items-center px-10 py-2 rounded-md border-blue border-4 space-y-4 " 
                      style={{background: '#c09639', opacity: '1'}}>
                        <h4 className='font-semibold text-md text-center'>Class X Toppers</h4>
                        <Image style={{ width: "auto", height: "auto" }} className='rounded-3xl' src='/students/Ritesh-Singh.png' width={160} height={150} alt='image' />
                        <p className='font-normal'>Ritesh Singh</p>
                      </div>
                    </SwiperSlide>

                    <SwiperSlide>
                      <div className="item-1 flex flex-col items-center px-10 py-2 rounded-md border-blue border-4 space-y-4 "
                       style={{background: '#c09639', opacity: '1'}}>
                        <h4 className='font-semibold text-md text-center'>Class X Toppers</h4>
                        <Image style={{ width: "auto", height: "auto" }} className='rounded-3xl' src='/students/Kashish-Singh.png' width={160} height={150} alt='image' />
                        <p className='font-normal'>Kashish Singh</p>
                      </div>
                    </SwiperSlide>

                  </Swiper>
                </div>

              </div>

            </div>

          </div>
        </section>


        {/* Beyound Academics */}
        <section data-aos="fade-right">
          <div className="galleryy flex flex-col items-center my-10 mx-auto px-2">
            <div className="section-heading flex text-center md:block">
              <h2 className={styles.sectionTitle}>BEYOND ACADEMICS</h2>
            </div>

            <div>
              <section className="text-gray-600 body-font">
                <div className="container px-5 py-24 mx-auto">
                  <div className="flex flex-wrap -mx-4 -my-8">


                    {EventList?.slice(0, 4).map((item, index) => (

                      <div key={index} className="py-8 px-4 lg:w-1/4">
                        <div className="h-full flex items-start">
                          <div className="w-12 flex-shrink-0 flex flex-col text-center leading-none">
                            <span className="text-gray-500 pb-2 mb-2 border-b-2 border-gray-200">{item.eventDate.split('-')[1]}</span>
                            <span className="font-medium pb-2 text-lg text-gray-800 title-font leading-none">{item.eventDate.split('-')[0]}</span>
                            {/* <span className="font-medium pb-2 text-lg text-gray-800 title-font leading-none">{item.eventDate.split('-')[2]}</span> */}
                          </div>
                          <div className="flex-grow pl-6">
                            <h2 className="tracking-widest text-xs title-font font-medium text-indigo-500 mb-1">SPORTS</h2>
                            <div className="rounded-lg h-64 overflow-hidden">
                              <img alt="content" className="object-cover object-center h-full w-full" src={item.image} />
                            </div>
                            <h1 className="title-font text-xl font-medium text-gray-900 mb-3">{item.name}</h1>
                            <p className="leading-relaxed mb-5">{item.description}</p>
                            <a className="inline-flex items-center">
                              <img alt="blog" src={item.image} className="w-8 h-8 rounded-full flex-shrink-0 object-cover object-center" />
                              <span className="flex-grow flex flex-col pl-3">
                                <span className="title-font font-medium text-gray-900">SAGES</span>
                              </span>
                            </a>
                          </div>
                        </div>
                      </div>
                    ))}

                  </div>
                </div>
              </section>
            </div>

          </div>
        </section>



        {/* Our Gallery Section */}
        <section className="text-gray-600 body-font" data-aos="fade-up">
          <div className="galleryy flex flex-col items-center my-10 mx-auto px-2">

            <div className="section-heading ">
              <h2 className={styles.sectionTitle}>Our Gallery</h2>
            </div>

            <div className="container py-12 mx-auto flex flex-wrap bg-slate-100">
              <div className="flex flex-col justify-center items-center text-center w-full mb-20 flex-wrap bg-[#d6a026] text-white p-10 md:mx-7 rounded-lg">
                <h1 className="sm:text-3xl text-2xl font-medium title-font lg:w-1/3 lg:mb-0 mb-4 text-white">"Sages Gallery: Capturing Moments, Inspiring Futures"</h1>
                <p className="lg:pl-6 lg:w-2/3 mx-auto leading-relaxed text-base text-[#e3e3e9]">Explore the Essence of Sages through a Visual Journey of Academic Excellence, Creativity, and Community Spirit</p>
              </div>
              <div className="flex flex-col md:flex-row md:flex-wrap md:-m-2 -m-1">

                <div className="flex flex-wrap w-full md:w-1/2">

                  <div className="md:p-2 p-1 w-1/2">
                    <img alt="gallery" className="w-full object-cover h-full object-center block" src="/slider/aatma.png" />
                  </div>
                  <div className="md:p-2 p-1 w-1/2">
                    <img alt="gallery" className="w-full object-cover h-full object-center block" src="/slider/aatma3.png" />
                  </div>
                  <div className="md:p-2 p-1 w-full">
                    <img alt="gallery" className="w-full h-full object-cover object-center block" src="/slider/aatma4.png" />
                  </div>

                </div>

                <div className="flex flex-wrap w-full md:w-1/2">

                  <div className="md:p-2 p-1 w-full">
                    <img alt="gallery" className="w-full h-full object-cover object-center block" src="/slider/aatma2.png" />
                  </div>
                  <div className="md:p-2 p-1 w-1/2">
                    <img alt="gallery" className="w-full object-cover h-full object-center block" src="/slider/aatma.png" />
                  </div>
                  <div className="md:p-2 p-1 w-1/2">
                    <img alt="gallery" className="w-full object-cover h-full object-center block" src="/slider/aatma2.png" />
                  </div>

                </div>

              </div>
              <div className="flex mt-4 w-full mx-auto justify-end ">

                <Link href={'/gallery'} className="text-white border-orange-300 border-2 rounded-xl px-3 py-2 inline-flex items-center font-semibold bg-orange-500 hover:bg-orange-600 md:mb-2 lg:mb-0">Explore
                  <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
                </Link>

              </div>
            </div>


          </div>


        </section>

        {/* Stats Section */}
        <section className="stats" data-aos="fade-right">
          <div className="st flex flex-col items-center my-10 px-2">
            <div className="section-heading">
              <h2 className={styles.sectionTitle}>Our School</h2>
            </div>

            <div className="statsContainer flex flex-col space-y-3 md:space-y-1 md:flex-row justify-center space-x-2 md:space-x-36 my-10">

              <div className='flex flex-col justify-center items-center '>
                <Image style={{ width: "auto", height: "auto" }} src='/stats/students.png' width={91} height={94} alt='image' />
                <span>121</span>
                <p>Students</p>
              </div>

              <div className='flex flex-col justify-center items-center'>
                <Image style={{ width: "auto", height: "auto" }} src='/stats/classroom.png' width={91} height={94} alt='image' />
                <span>12</span>
                <p>Classroom</p>
              </div>

              <div className='flex flex-col justify-center items-center'>
                <Image style={{ width: "auto", height: "auto" }} src='/stats/teacher.png' width={91} height={94} alt='image' />
                <span>40</span>
                <p>Teachers</p>
              </div>

              <div className='flex flex-col justify-center items-center'>
                <Image style={{ width: "auto", height: "auto" }} src='/stats/bus.png' width={91} height={94} alt='image' />
                <span>3</span>
                <p>School Bus</p>
              </div>

            </div>
          </div>
        </section>

        {/* Testinomial */}
        <section className="text-gray-600 body-font mb-4">
          <div className="section-heading flex justify-center w-full mb-4">
            <h2 className={styles.sectionTitle}>Testinomial</h2>
          </div>
          <div className="flex w-[100%] justify-center items-center px-auto ">

            <div className="flex flex-col justify-center items-center mx-auto px-5 bg-slate-100 rounded-lg shadow-lg py-3">
              <img alt="testimonial" className="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100" src="/students/nikhil.jpg" />
              <p className="leading-relaxed w-[70vw] text-center py-2 md:px-20">It has been an absolute pleasure collaborating with Mr. Nikhil Dasar on the development of our school website. As a web developer, Mr. Nikhil Dasar has demonstrated an unparalleled level of expertise, professionalism, and dedication to delivering a digital platform that exceeds our expectations</p>
              <span className="inline-block h-1 w-10 rounded bg-yellow-500 mt-6 mb-4"></span>
              <h2 className="text-orange-900 font-bold title-font tracking-wider text-md flex text-center">Nikhil Dasar</h2>
              <p className="text-orange-700 flex text-center">Software Engineer <br />Full Stack Web & Android Developer</p>
            </div>



          </div>
        </section>

        <button
          className={`fixed flex justify-center z-30 items-center bottom-4 right-4 bg-[#ffc107] hover:bg-[#ffc107d9] text-white w-10 h-10 px-auto rounded-full ${isVisible ? 'opacity-100' : 'opacity-0 pointer-events-none'
            } transition-opacity duration-300 ease-in-out`}
          onClick={scrollToTop}
        >
          <svg xmlns="http://www.w3.org/2000/svg" height="16" width="12" viewBox="0 0 384 512">
            <path fill="#ffffff" d="M214.6 41.4c-12.5-12.5-32.8-12.5-45.3 0l-160 160c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L160 141.2V448c0 17.7 14.3 32 32 32s32-14.3 32-32V141.2L329.4 246.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-160-160z" /></svg>
        </button>




      </main >
    </>
  )
}


// export async function getServerSideProps(context) {
//   let nLinks;
//   try {
//     if (!mongoose.connections[0].readyState) {
//       await mongoose.connect(process.env.MONGO_URI);
//     }

//     nLinks = await Notice.find();
//     // Pass data to the page via props
//     return { props: { nLinks: JSON.parse(JSON.stringify(nLinks)) } }

//   } catch (error) {
//     console.log({ error: "Server side props nLinks home" });
//     // Pass data to the page via props
//     return { props: {} }
//   }


// }


